version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "18:00"
      timezone: America/Los_Angeles
    allow:
      - dependency-type: production
    rebase-strategy: disabled
    open-pull-requests-limit: 5
