language: node_js

services:
  - docker

before_install:
  - docker-compose -f docker-compose-test.yml pull
  - docker-compose -f docker-compose-test.yml build api
  - cd app && npm install

script:
  - docker-compose -f docker-compose-test.yml run --rm api npm test
  - cd app && npm test
