language: bash

services:
  - docker

before_install:
  - docker-compose  -f docker-compose-travis.yml pull
  - docker-compose -f docker-compose-travis.yml build api

script:
  - docker-compose -f docker-compose-travis.yml run --rm api npm test
