language: node_js
  - "11.4.0"

services:
  - docker

before_install:
  - docker-compose -f docker-compose-test.yml build api app data

script:
  - docker-compose -f docker-compose-test.yml run --rm app npm run test
  - docker-compose -f docker-compose-test.yml run --rm api npm run test
  #- docker-compose -f docker-compose-test.yml run --rm data make test

before_deploy:
  - sudo add-apt-repository -y ppa:eugenesan/ppa
  - sudo apt-get update -y
  - sudo apt-get install jq -y
  - pip install --user awscli

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: ecs-work
