language: node_js
  - "11.4.0"

services:
  - docker

cache:
  directories:
    - app/node_modules

before_install:
  - docker-compose -f docker-compose-test.yml build api
  - docker-compose -f docker-compose-test.yml build data
  - cd /home/travis/build/hackoregon/openelections/app
  - yarn install

script:
  - cd /home/travis/build/hackoregon/openelections
  - docker-compose -f docker-compose-test.yml run --rm api npm test
  - docker-compose -f docker-compose-test.yml run --rm data make test
  - cd /home/travis/build/hackoregon/openelections/app
  - yarn test
  - cd /home/travis/build/hackoregon/openelections

before_deploy:
  - sudo add-apt-repository -y ppa:eugenesan/ppa
  - sudo apt-get update -y
  - sudo apt-get install jq -y
  - pip install --user awscli

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: ecs-work
