language: bash

services:
  - docker

before_install:
  - docker-compose -f docker-compose-test.yml pull
  - docker-compose -f docker-compose-test.yml build api

script:
  - docker-compose -f docker-compose-test.yml run --rm api npm test
