version: '3'
services:
  app:
    tty: true
    image: openelections-app-production
    build:
      context: 'app'
      dockerfile: 'Dockerfile.production'
    ports:
      - 80:80
  api:
    tty: true # Enables debugging capabilities when attached to this container.
    user: root
    image: openelections-api-production
    build:
      context: 'api'
      dockerfile: 'Dockerfile.production'

