version: '3'
services:
  app:
    tty: true
    build:
      context: 'app'
      dockerfile: 'Dockerfile.development'
    command: ["npm", "start"]
    environment:
      - PORT=4000
    depends_on:
      - testdb
    ports:
      - 4000:4000
    networks:
      - openelections
  api:
    tty: true # Enables debugging capabilities when attached to this container.
    user: root
    build:
      context: 'api'
      dockerfile: 'Dockerfile.development'
#    volumes:
#      - ./api:/app
    command: ["./wait-for-it.sh", "db:5433", "--", "npm", "run", "develop"]
    environment:
      - PORT=3000
      - NODE_ENV=test
      - SECRET_KEY=bananas
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=open_elections_test
      - DB_HOST=testdb
      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
      - DB_PORT=5432
    depends_on:
      - testdb
    ports:
      - 3000:3000
    networks:
      - openelections
  testdb:
    image: mdillon/postgis
    ports: ['5434:5432']
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=open_elections_test
    networks:
      - openelections
networks:
  openelections:


