version: '3'
services:
  app:
    tty: true
    image: openelections-app-production
    build:
      context: 'app'
      dockerfile: 'Dockerfile.production'
    ports:
      - "4000:4000"
  api:
    tty: true # Enables debugging capabilities when attached to this container.
    user: root
    image: openelections-api-production
    build:
      context: 'api'
      dockerfile: 'Dockerfile.production'
    ports:
    - "3000:3000"
    environment:
      - "DB_HOST="
      - "DB_NAME="
      - "DB_PORT=5432"
      - "DB_USERNAME="
      - "HOST_URL=openelectionsportland.org"
      - "NODE_ENV=production"
      - "PORT=3000"
      - "DB_PASSWORD="
      - "SECRET_KEY=bananas"

