version: '3'
services:
  app:
    tty: true
    build:
      context: 'app'
      dockerfile: 'Dockerfile.development'
    command: ["npm", "start"]
    environment:
      - PORT=4000
    depends_on:
      - db
    ports:
      - 4000:4000
    networks:
      - openelections
  api:
    tty: true # Enables debugging capabilities when attached to this container.
    user: root
    build:
      context: 'api'
      dockerfile: 'Dockerfile.development'
    # command: npm run development
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "develop"]
    environment:
      - PORT=3000
      - NODE_ENV=development
      - SECRET_KEY=bananas
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=open_elections_dev
      - DB_HOST=db
      - DB_PORT=5432
      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=djcmTZHzA:6c4+P%2[P*SYxcvX9ma|KWyN$gnD{h
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    networks:
      - openelections
  redis:
    image: redis
    ports: ['6379:6379']
    networks:
      - openelections
  db:
    image: mdillon/postgis
    ports: ['5432:5432']
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=open_elections_dev
    networks:
      - openelections
  data_db:
    image: mdillon/postgis
    ports: ['5433:5432']
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=open_elections_data
    networks:
      - openelections
  data:
    build:
      context: ./2019-openelections-data
    volumes:
      - ./2019-openelections-data:/project/root
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=open_elections_data
networks:
  openelections:


