version: '3'
services:
  app:
    tty: true
    build:
      context: 'app'
      dockerfile: 'Dockerfile'
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    networks:
      - openelections
    volumes:
      - ./app:/app
  api:
    tty: true # Enables debugging capabilities when attached to this container.
    user: root
    build:
      context: 'api'
      dockerfile: 'Dockerfile.qa'
    env_file:
      - .env.qa
    depends_on:
      - redis
      # - data
    ports:
      - 3000:3000
    volumes:
      - ./api/controller:/app/controller
      - ./api/models:/app/models
      - ./api/routes:/app/routes
      - ./api/services:/app/services
      - ./api/test:/app/test
      - ./api/types:/app/types
      - ./api/jobs:/app/jobs
      - ./api/.nvmrc:/app/.nvmrc
      - ./api/app.ts:/app/app.ts
      - ./api/package.json:/app/package.json
      - ./api/tsconfig.json:/app/tsconfig.json
    networks:
      - openelections
  redis:
    image: redis
    ports: ['6379:6379']
    networks:
      - openelections
  networks:
    openelections:
  # data:
  #   build:
  #     context: ./datascience
  #   volumes:
  #     - ./datascience:/app
  #   ports: ["8080:80"]
  #   env_file:
  #     - .env.qa
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=open_elections_dev
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_HOST=db
  #     - FLASK_ENV=development
  #   command: ["sh", "/app/openelections/api/start.sh"]
  #   networks:
  #     - openelections
  # jobs:
  #   tty: true # Enables debugging capabilities when attached to this container.
  #   user: root
  #   build:
  #     context: 'api'
  #     dockerfile: 'Dockerfile.jobs'
  #   env_file:
  #     - .env.qa
  #   depends_on:
  #     - redis
  #     - data
  #   volumes:
  #     - ./api/controller:/app/controller
  #     - ./api/models:/app/models
  #     - ./api/routes:/app/routes
  #     - ./api/services:/app/services
  #     - ./api/test:/app/test
  #     - ./api/types:/app/types
  #     - ./api/jobs:/app/jobs
  #     - ./api/.nvmrc:/app/.nvmrc
  #     - ./api/app.ts:/app/app.ts
  #     - ./api/package.json:/app/package.json
  #     - ./api/tsconfig.json:/app/tsconfig.json
  #   networks:
  #     - openelections



