export const ADDON_ID: any;
export const EVENT_ID: any;
export const PANEL_ID: any;
export const action: any;
export const actions: any;
export const configureActions: any;
export const decorate: any;
export const decorateAction: any;
export const withActions: any;
