FROM node:11.4.0 as build-stage

WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install --production

COPY . /app

RUN npm run build

FROM nginx:1.16-alpine
COPY --from=build-stage /app/build/ /usr/share/nginx/html
COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/default.conf

RUN apk add --no-cache curl

CMD ["nginx", "-g", "daemon off;"]
