FROM node:11.4.0 as build-stage

WORKDIR /app
COPY package.json .
RUN npm install

COPY . /app

RUN npm run build

FROM nginx:1.15
COPY --from=build-stage /app/build/ /usr/share/nginx/html
COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/default.conf



