/** Declaration file generated by dts-gen */

export function clearMessages(...args: any[]): void;

export function flashErrorMessage(message: any, options: any): any;

export function flashMessage(message: any, ...args: any[]): any;

export function flashMessageType(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;

export function flashSuccessMessage(message: any, ...args: any[]): any;

export function getErrorMessages(state: any): any;

export function getFlashMessages(state: any): any;

export function getLatestMessage(state: any): any;

export function getSuccessMessages(state: any): any;

export function middleware(...args: any[]): any;

export function reducer(state: any, action: any): any;

export function removeMessage(...args: any[]): void;

export namespace clearMessages {
    function toString(): any;

}

export namespace flashMessageType {
    function isRequired(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;

}

export namespace removeMessage {
    function toString(): any;

}

