FROM node:18.16.0

RUN apt-get update -y && apt-get install -y gdal-bin

WORKDIR /app
COPY package.json .
COPY package-lock.json .

RUN npm install
COPY . /app

COPY wait-for-it.sh .

EXPOSE 3000
CMD ["npm", "run", "develop"]
