FROM node:11.4.0
LABEL maintainer "Dan Melton <dan@civicsoftwarefoundation.org>"
WORKDIR /app
COPY package.json .

RUN npm install
COPY . /app

COPY wait-for-it.sh .

EXPOSE 3000
CMD ["npm", "run", "seedandrun"]
